Используя модуль array и библиотеку numpy, решить следующие задачи:
а) Дан массив A размера N. Сформировать новый массив B того же размера по следующему правилу: элемент BK равен сумме элементов массива A с номерами от 1 до K.

In [1]:
import array

# Создаем массив A
A = array.array('i', [1, 2, 3, 4, 5])  # 'i' означает тип данных integer

# Инициализируем массив B
B = array.array('i', [0]*len(A))

# Заполняем массив B
current_sum = 0
for i in range(len(A)):
    current_sum += A[i]
    B[i] = current_sum

print("Массив B:", list(B))


Массив B: [1, 3, 6, 10, 15]


In [2]:
import numpy as np

# Создаем массив A
A = np.array([1, 2, 3, 4, 5])

# Используем cumsum для получения массива B
B = np.cumsum(A)

print("Массив B:", B)


Массив B: [ 1  3  6 10 15]


б) Дана матрица размера M×N. Элемент матрицы называется ее локальным минимумом, если он меньше всех окружающих его элементов. Заменить все локальные минимумы данной матрицы на нули.

In [3]:
import numpy as np

# Функция для проверки и замены локальных минимумов
def replace_local_minima(matrix):
    M, N = matrix.shape
    # Копируем матрицу для безопасной модификации
    new_matrix = np.copy(matrix)
    
    # Перебираем каждый элемент матрицы
    for i in range(M):
        for j in range(N):
            # Проверяем всех соседей элемента matrix[i, j]
            current = matrix[i, j]
            is_minima = True
            
            # Проверка соседей по вертикали и горизонтали
            for di in [-1, 0, 1]:
                for dj in [-1, 0, 1]:
                    if di == 0 and dj == 0:
                        continue
                    ni, nj = i + di, j + dj
                    if 0 <= ni < M and 0 <= nj < N:
                        if matrix[ni, nj] <= current:
                            is_minima = False
            
            # Если элемент является локальным минимумом, заменяем его на ноль
            if is_minima:
                new_matrix[i, j] = 0
    
    return new_matrix

# Пример матрицы
matrix = np.array([
    [9, 2, 3, 4],
    [5, 6, 7, 8],
    [1, 2, 3, 1]
])

# Замена локальных минимумов и вывод результата
modified_matrix = replace_local_minima(matrix)
print("Исходная матрица:\n", matrix)
print("Модифицированная матрица:\n", modified_matrix)


Исходная матрица:
 [[9 2 3 4]
 [5 6 7 8]
 [1 2 3 1]]
Модифицированная матрица:
 [[9 0 3 4]
 [5 6 7 8]
 [0 2 3 0]]


In [5]:
import numpy as np

def replace_local_minima(matrix):
    M, N = matrix.shape
    # Создаём новую матрицу, которая исходно равна данной матрице
    new_matrix = np.copy(matrix)
    
    # Расширяем матрицу, добавляя максимальное значение +1 по краям для упрощения сравнения
    max_val = np.max(matrix) + 1
    padded_matrix = np.pad(matrix, pad_width=1, mode='constant', constant_values=max_val)
    
    # Перебираем все возможные направления смещения для поиска соседей
    for di in [-1, 0, 1]:
        for dj in [-1, 0, 1]:
            if di == 0 and dj == 0:
                continue
            # Сравниваем элементы с их соседями
            new_matrix = np.minimum(new_matrix, padded_matrix[1+di:M+1+di, 1+dj:N+1+dj])
    
    # Заменяем локальные минимумы (те, что равны исходным элементам) на нули
    new_matrix[(new_matrix == matrix) & (new_matrix != max_val)] = 0
    
    return new_matrix

# Пример матрицы
matrix = np.array([
    [9, 2, 3, 4],
    [5, 6, 7, 8],
    [1, 2, 3, 1]
])

# Замена локальных минимумов и вывод результата
modified_matrix = replace_local_minima(matrix)
print("Исходная матрица:\n", matrix)
print("Модифицированная матрица:\n", modified_matrix)


Исходная матрица:
 [[9 2 3 4]
 [5 6 7 8]
 [1 2 3 1]]
Модифицированная матрица:
 [[2 0 2 3]
 [1 1 1 1]
 [0 1 1 0]]


Дан стек. Необходимо проверить, является ли его содержимое палиндромом (то есть читается одинаково как слева направо, так и справа налево).

In [9]:
class Stack:
    def __init__(self):
        self.items = []
    
    def push(self, item):
        self.items.append(item)
    
    def pop(self):
        if not self.is_empty():
            return self.items.pop()
        return None

    
    def is_empty(self):
        return len(self.items) == 0

def is_palindrome(stack):
    original_content = []
    
    # Извлекаем элементы из стека
    while not stack.is_empty():
        original_content.append(stack.pop())
    
    # Проверяем, является ли содержимое палиндромом
    return original_content == original_content[::-1]

# Пример использования
stack = Stack()
for char in "radar":
    stack.push(char)

print("Стек является палиндромом:", is_palindrome(stack))


Стек является палиндромом: True


Создать класс двусторонней очереди, который будет поддерживать операции добавления элемента в начало и конец очереди, удаления элемента из начала и конца очереди, а также удаления минимального и максимального элементов из очереди.

In [10]:
class Deque:
    def __init__(self):
        self.items = []
    
    def add_front(self, item):
        """Добавляет элемент в начало очереди."""
        self.items.insert(0, item)
    
    def add_rear(self, item):
        """Добавляет элемент в конец очереди."""
        self.items.append(item)
    
    def remove_front(self):
        """Удаляет и возвращает элемент из начала очереди."""
        if self.items:
            return self.items.pop(0)
        return None
    
    def remove_rear(self):
        """Удаляет и возвращает элемент из конца очереди."""
        if self.items:
            return self.items.pop()
        return None
    
    def delete_min(self):
        """Удаляет минимальный элемент из очереди."""
        if self.items:
            min_item = min(self.items)
            self.items.remove(min_item)
    
    def delete_max(self):
        """Удаляет максимальный элемент из очереди."""
        if self.items:
            max_item = max(self.items)
            self.items.remove(max_item)
    
    def is_empty(self):
        """Проверяет, пуста ли очередь."""
        return len(self.items) == 0
    
    def size(self):
        """Возвращает размер очереди."""
        return len(self.items)

# Пример использования
deque = Deque()
deque.add_front(3)
deque.add_rear(5)
deque.add_front(1)
deque.add_rear(10)

print("Элементы очереди:", deque.items)
print("Удалён из начала:", deque.remove_front())
print("Удалён из конца:", deque.remove_rear())
deque.delete_min()
print("Очередь после удаления минимального элемента:", deque.items)
deque.delete_max()
print("Очередь после удаления максимального элемента:", deque.items)


Элементы очереди: [1, 3, 5, 10]
Удалён из начала: 1
Удалён из конца: 10
Очередь после удаления минимального элемента: [5]
Очередь после удаления максимального элемента: []
